--- #YAML:1.0
name:                CPAN-Testers-WWW-Preferences
version:             0.18
abstract:            The CPAN Testers Preferences website
author:
  - Barbie <barbie@cpan.org>

license:             artistic_2
distribution_type:   module
installdirs:         site

requires:
  perl:                               5.006
  Labyrinth:                          5.20
  Labyrinth::DIUtils::ImageMagick:    5.04
  Labyrinth::Plugin::Core:            5.14
  Labyrinth::Plugin::CPAN:            3.50
  Class::Accessor::Fast:              0
  Data::Dumper:                       0
  Digest::SHA:                        0
  Email::Address:                     0
  MIME::Base64:                       0
  Net::SSLeay:                        0
  Sort::Versions:                     0
  Time::Local:                        0
recommends:
  Test::CPAN::Meta:                   0
  Test::CPAN::Meta::JSON:             0
  Test::Pod:                          1.00
  Test::Pod::Coverage:                0.08
build_requires:
  IO::File:                           0
  Test::More:                         0.70

provides:
  CPAN::Testers::WWW::Preferences:
    file:     lib/CPAN/Testers/WWW/Preferences.pm
    version:  0.18
  Labyrinth::Plugin::CPAN::Preferences:
    file:     lib/Labyrinth/Plugin/CPAN/Preferences.pm
    version:  0.18

no_index:
  directory:
    - examples
    - t
    - vhost

resources:
  homepage:   https://prefs.cpantesters.org
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-Testers-WWW-Preferences
  repository: http://github.com/barbie/cpan-testers-www-preferences

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: The Hand of Barbie 1.0
